### ISSUE TITLE
Thucydides Teamcity steplistener' not working after upgrading from Thucydides to Serenity

### ISSUE THREAD

**Issue by bvpadmanaban** [vase4kin/thucydides-teamcity-steplistener#17]
I have the below dependency in pom.xml for the Thucydides Teamcity steplistener,

```
    <dependency>
        <groupId>com.github.crystalservice</groupId>
        <artifactId>thucydides-teamcity-steplistener</artifactId>
        <version>0.3.7</version>
    </dependency>
```

While execution, I am getting the below exception after upgrade to Serenity.

java.lang.NoSuchMethodError: net.thucydides.core.model.TestOutcome.getMethodName()Ljava/lang/String;
    at com.github.crystalservice.TeamCityStepListener.getResultTitle(TeamCityStepListener.java:250)
    at com.github.crystalservice.TeamCityStepListener.printTestStarted(TeamCityStepListener.java:264)
    at com.github.crystalservice.TeamCityStepListener.testFinished(TeamCityStepListener.java:128)
    at net.thucydides.core.steps.StepEventBus.testFinished(StepEventBus.java:221)
    at net.serenitybdd.jbehave.SerenityReporter.afterScenario(SerenityReporter.java:529)
    at org.jbehave.core.reporters.DelegatingStoryReporter.afterScenario(DelegatingStoryReporter.java:43)
    at org.jbehave.core.reporters.ConcurrentStoryReporter.afterScenario(ConcurrentStoryReporter.java:173)
    at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:316)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
    at java.util.concurrent.FutureTask.run(FutureTask.java:166)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

**Comment by vase4kin** [comment]
Hello,
The listener was written for Thucydides. Seems that there are some api changes in Serenity. I will have a look for possibility to make new release with serenity support. I will keep you posted. 
Btw, thucydides-teamcity-steplistener moved from com.github.crystalservice. Please, see README for more details.

**Comment by vase4kin** [comment]
@bvpadmanaban what version of Serenity are you using?

**Comment by bvpadmanaban** [comment]
Thanks for updating the thucydides-teamcity-listerner to serenity. I am using serenity with 1.0.45.

**Comment by vase4kin** [comment]
@bvpadmanaban, i released [Serenity teamcity steplistener](https://github.com/vase4kin/serenity-teamcity-steplistener). You need to change your dependency in order to use it:

```
    <dependency>
        <groupId>com.github.vase4kin</groupId>
        <artifactId>serenity-teamcity-steplistener</artifactId>
        <version>1.0.0</version>
    </dependency>
```

Could you please reply me about your results?

**Comment by bvpadmanaban** [comment]
Awesome... It is perfectly working fine in my UI(Webdriver) and Web services Automation and showing Serenity Tests count in Team city. Thanks a lot.

**Comment by vase4kin** [comment]
@bvpadmanaban Good news, have a good day!
